### ISSUE TITLE
No option for Blender in Speckle.exe

### ISSUE THREAD

**Issue by grootstebozewolf** [speckleworks/SpeckleInstaller#16]
Step 0: 
- [x] I've  read the [contribution guidelines](https://github.com/speckleworks/SpeckleOrg/blob/master/CONTRIBUTING.md)!
#### Expected Behaviour
When you start speckle.exe it should have an option for Speckle for Blender and setup the database that is shared between Rhino, Dynamo and Grasshoper or can be used on its own.

#### Actual Behaviour
There is no Speckle for Blender option, so it can't be used on its own.

#### Affected Projects
No

#### Reproduction Steps & System Config (win, osx, web, etc.)
Windows 10
Blender 2.81.1
PySpeckle 1.1.0
#### Proposed Solution (if any)
Install empty database and configure installed Blender configuration.

**Comment by tsvilans** [comment]
> @tsvilans, we (read: @mishaelnuh) are now looking at revamping the installer and how we distribute speckle to people, and of course we would be more than happy to include Blender!
> 
> I'll move this issue to the SpeckleInstaller in the meantime.

@didimitrie I think the question here more relates to the `SpeckleCache.db` file that gets created by the .NET client. Perhaps this should be installed with Speckle so that it's coordinated and available for all clients?

**Comment by JanFilipec** [comment]
So, is there a way to get speckle runing on Blender/Windows? I can't activate the plugin in blender (2.91)

Traceback (most recent call last):
  File "C:\PortableApps\BlenderPortable\App\Blender64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\PortableApps\BlenderPortable\Data\user_scripts\addons\bpy_speckle\__init__.py", line 53, in <module>
    from speckle import SpeckleApiClient, SpeckleCache
ModuleNotFoundError: No module named 'speckle'

and I can't install the blender client, because the setup only allows me to pick GH or Revit

![image](https://user-images.githubusercontent.com/67052298/108429888-dd3a7000-7240-11eb-977c-aef7589bbe10.png)

Or did I just uderstand the system wrong?

**Comment by daviddekoning** [comment]
Hi @JanFilipec - yeah, the Blender client installation is completely separate from the Revit, Rhino, etc... clients. 

It looks like you are missing the Speckle Python library, you can install it with:

```
pip install speckle 
```

**Comment by tsvilans** [comment]
Try restarting Blender. If it worked correctly, it should `pip install speckle` automagically, but it might need some coercion.

**Comment by JanFilipec** [comment]
Ok thanks a lot, it worked now.
May I suggest adding a few more sentences about this proces to the first run description in the Speckle Blender readme?
Something along the lines "Speckle for Blender is currently not part of the Windows installer, it will be installed automatically by the python package manager pip after enabling the add-on in Blender. If the automatic installation doesn't work, try installing pip separately."
